/* Copyright (c) <2003-2021> <Newton Game Dynamics>
* 
* This software is provided 'as-is', without any express or implied
* warranty. In no event will the authors be held liable for any damages
* arising from the use of this software.
* 
* Permission is granted to anyone to use this software for any purpose,
* including commercial applications, and to alter it and redistribute it
* freely
*/

#include "newtonStdafx.h"
#include "newtonWorld.h"
#include "newtonBodyNotify.h"

ndNewtonBodyNotify::ndNewtonBodyNotify(NewtonBody* const owner)
	:ndModelBodyNotify()
	,m_userData(nullptr)
	,m_owner(owner)
	,m_materialGoupId(0)
	,m_capSpeed(ndFloat32 (20.0f))
	,m_capOmega(ndFloat32(10.0f))
	,m_bodyIsInWorld(false)
	,m_applyTransform(nullptr)
	,m_forceAndTorque(nullptr)
{
}

ndNewtonBodyNotify::ndNewtonBodyNotify(const ndNewtonBodyNotify& notify)
	:ndModelBodyNotify(notify)
	,m_userData(notify.m_userData)
	,m_owner(notify.m_owner)
	,m_materialGoupId(notify.m_materialGoupId)
	,m_capSpeed(notify.m_capSpeed)
	,m_capOmega(notify.m_capOmega)
	,m_bodyIsInWorld(false)
	,m_applyTransform(notify.m_applyTransform)
	,m_forceAndTorque(notify.m_forceAndTorque)
{
}

ndNewtonBodyNotify::~ndNewtonBodyNotify()
{
}

ndBodyNotify* ndNewtonBodyNotify::Clone() const
{
	return new ndNewtonBodyNotify(*this);
}


void ndNewtonBodyNotify::OnBodyAddedToWorld()
{
	m_bodyIsInWorld = true;
}

void ndNewtonBodyNotify::OnBodyRemovedFromWorld()
{
	m_bodyIsInWorld = false;
}

void ndNewtonBodyNotify::OnApplyExternalForce(ndInt32 threadIndex, ndFloat32 timestep)
{
	ndBodyKinematic* const body = GetBody()->GetAsBodyKinematic();
	if (body->GetInvMass() > 0.0f)
	{
		// Clamp huge angular and linear velocities generated by high speed collisions
		// or stiff joints loops
		ndVector omega(body->GetOmega());
		ndVector veloc(body->GetVelocity());
		ndFloat32 omega2(omega.DotProduct(omega).GetScalar());
		if (omega2 > m_capOmega * m_capOmega)
		{
			omega = omega.Normalize().Scale(m_capOmega);
			body->SetOmega(omega);
		}
	
		ndFloat32 veloc2(veloc.DotProduct(veloc).GetScalar());
		if (veloc2 > m_capSpeed * m_capSpeed)
		{
			veloc = veloc.Normalize().Scale(m_capSpeed);
			body->SetVelocity(veloc);
		}
	}

	if (m_forceAndTorque)
	{
		m_forceAndTorque(*m_owner, timestep, threadIndex);
	}
}


void ndNewtonBodyNotify::OnTransform(ndFloat32, const ndMatrix& matrix)
{
	if (m_applyTransform)
	{
		m_applyTransform(*m_owner, &matrix[0][0], 0);
	}
	//// apply this transformation matrix to the application user data.
	//if (*m_entity)
	//{
	//	if (m_parentBody)
	//	{
	//		const ndMatrix parentMatrix(m_bindMatrix * m_parentBody->GetMatrix());
	//		const ndMatrix localMatrix(matrix * parentMatrix.OrthoInverse());
	//
	//		const ndQuaternion rot(localMatrix);
	//		m_transform = ndTransform(rot, localMatrix.m_posit);
	//	}
	//	else
	//	{
	//		m_transform = ndTransform(matrix * m_bindMatrix);
	//	}
	//}
	//
	//if (!CheckInWorld(matrix))
	//{
	//	RemoveBody();
	//}
}
