/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040401
#define SWIGC

	#pragma warning(disable:4127 4316 4365 4456 4701 4706)

#define SWIG_CException_Raise newton_SWIG_CException_Raise
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NOEXCEPT noexcept
#else
# define SWIG_NOEXCEPT throw()
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif

/* -----------------------------------------------------------------------------
 * clabels.swg
 *
 * Definitions of C specific preprocessor symbols.
 * ----------------------------------------------------------------------------- */

// this is used instead of default SWIGEXPORT symbol

#ifndef SWIGEXPORTC
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORTC
#   else
#     define SWIGEXPORTC __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORTC __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORTC
#   endif
# endif
#endif


#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <setjmp.h>

#define SWIG_contract_assert(expr, msg) if(!(expr)) { printf("%s\n", msg); SWIG_exit(0); } else


typedef struct SwigObj SwigObj;

/* SWIG Errors applicable to all language modules, values are reserved from -1 to -99 */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13



#ifdef __cplusplus
extern "C" {
#endif
SWIGEXPORTC int SWIG_exit(int code) { exit(code); }
#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif

#if defined(__cplusplus) && (__cplusplus >=201103L)
# define SWIG_OVERRIDE override
#else
# define SWIG_OVERRIDE
#endif



extern "C" SWIGEXPORTC void SWIG_CException_Raise(int code, const char* msg);


#ifndef SWIG_CException_DEFINED
class SWIG_CException {
public:
  SWIG_CException(const SWIG_CException& ex) throw() : code(ex.code), msg(strdup(ex.msg)) { }
  ~SWIG_CException() { free(const_cast<char*>(msg)); }

  const int code;
  const char* const msg;

  static SWIG_CException* get_pending() throw() {
    return PendingException;
  }

  static void reset_pending() throw() {
    if (PendingException) {
      delete PendingException;
      PendingException = 0;
    }
  }

private:
  friend void SWIG_CException_Raise(int code, const char* msg);

  static thread_local SWIG_CException* PendingException;

  SWIG_CException(int code, const char* msg) : code(code), msg(strdup(msg)) { }

  SWIG_CException& operator=(const SWIG_CException& ex);
};
#endif // SWIG_CException_DEFINED


#ifndef SWIG_CException_DEFINED
thread_local SWIG_CException *SWIG_CException::PendingException = 0;

SWIGEXPORTC void SWIG_CException_Raise(int code, const char* msg) {
  delete SWIG_CException::PendingException;
  SWIG_CException::PendingException = new SWIG_CException(code, msg);
}
#endif // SWIG_CException_DEFINED


#include <stdint.h>		// Use the C99 official header


	#include <ndNewtonInc.h>
	//#include <install/source/ndTypes.h>
	//#include <newtonWorld.h>
	#include "newtonConfig.h"
	//#include <ndWorld.h>

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORTC SwigObj* SWIG_CException_copy(SwigObj* carg1) {
  SWIG_CException *cppresult;
  SWIG_CException *arg1 = 0 ;
  SwigObj* result;
  
  
  arg1 = (SWIG_CException *) carg1;
  
  cppresult = (SWIG_CException *)new SWIG_CException((SWIG_CException const &)*arg1);
  result = (SwigObj*) cppresult;
  return result;
}


SWIGEXPORTC void SWIG_CException_delete(SwigObj* carg1) {
  SWIG_CException *arg1 = 0 ;
  
  arg1 = (SWIG_CException *) carg1;
  delete arg1;
}


SWIGEXPORTC int SWIG_CException_code_get(SwigObj* carg1) {
  int cppresult;
  SWIG_CException *arg1 = 0 ;
  int result;
  
  arg1 = (SWIG_CException *) carg1;
  cppresult = (int)(int) ((arg1)->code);
  result = (int)cppresult;
  return result;
}


SWIGEXPORTC char * SWIG_CException_msg_get(SwigObj* carg1) {
  char *cppresult;
  SWIG_CException *arg1 = 0 ;
  char * result;
  
  arg1 = (SWIG_CException *) carg1;
  cppresult = (char *)(char *) ((arg1)->msg);
  result = (char *)cppresult;
  return result;
}


SWIGEXPORTC SwigObj* SWIG_CException_get_pending() {
  SWIG_CException *cppresult;
  SwigObj* result;
  
  cppresult = (SWIG_CException *)SWIG_CException::get_pending();
  result = (SwigObj*) cppresult;
  return result;
}


SWIGEXPORTC void SWIG_CException_reset_pending() {
  SWIG_CException::reset_pending();
}


SWIGEXPORTC float newton_ndExp_VS_Fix(float carg1) {
  ndFloat32 cppresult;
  ndReal arg1 ;
  float result;
  
  arg1 = (ndReal) carg1;
  cppresult = (ndFloat32)ndExp_VS_Fix(arg1);
  result = (float)cppresult;
  return result;
}


SWIGEXPORTC void ndFloatSign_m_iVal_set(SwigObj* carg1, int carg2) {
  ndFloatSign *arg1 = 0 ;
  int arg2 ;
  
  arg1 = (ndFloatSign *) carg1;
  arg2 = (int) carg2;
  if (arg1) (arg1)->m_iVal = arg2;
}


SWIGEXPORTC int ndFloatSign_m_iVal_get(SwigObj* carg1) {
  int cppresult;
  ndFloatSign *arg1 = 0 ;
  int result;
  
  arg1 = (ndFloatSign *) carg1;
  cppresult = (int) ((arg1)->m_iVal);
  result = (int)cppresult;
  return result;
}


SWIGEXPORTC void ndFloatSign_m_fVal_set(SwigObj* carg1, float carg2) {
  ndFloatSign *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (ndFloatSign *) carg1;
  arg2 = (float) carg2;
  if (arg1) (arg1)->m_fVal = arg2;
}


SWIGEXPORTC float ndFloatSign_m_fVal_get(SwigObj* carg1) {
  float cppresult;
  ndFloatSign *arg1 = 0 ;
  float result;
  
  arg1 = (ndFloatSign *) carg1;
  cppresult = (float) ((arg1)->m_fVal);
  result = (float)cppresult;
  return result;
}


SWIGEXPORTC SwigObj* ndFloatSign_new() {
  ndFloatSign *cppresult;
  SwigObj* result;
  
  cppresult = (ndFloatSign *)new ndFloatSign();
  result = (SwigObj*) cppresult;
  return result;
}


SWIGEXPORTC void ndFloatSign_delete(SwigObj* carg1) {
  ndFloatSign *arg1 = 0 ;
  
  arg1 = (ndFloatSign *) carg1;
  delete arg1;
}


SWIGEXPORTC SwigObj* ndIntPtr_new() {
  ndIntPtr *cppresult;
  SwigObj* result;
  
  cppresult = (ndIntPtr *)new ndIntPtr();
  result = (SwigObj*) cppresult;
  return result;
}


SWIGEXPORTC void ndIntPtr_m_ptr_set(SwigObj* carg1, void * carg2) {
  ndIntPtr *arg1 = 0 ;
  void *arg2 = 0 ;
  
  arg1 = (ndIntPtr *) carg1;
  arg2 = (void *) carg2;
  if (arg1) (arg1)->m_ptr = arg2;
}


SWIGEXPORTC void * ndIntPtr_m_ptr_get(SwigObj* carg1) {
  void *cppresult;
  ndIntPtr *arg1 = 0 ;
  void * result;
  
  arg1 = (ndIntPtr *) carg1;
  cppresult = (void *) ((arg1)->m_ptr);
  result = (void *)cppresult;
  return result;
}


SWIGEXPORTC void ndIntPtr_m_int_set(SwigObj* carg1, long long carg2) {
  ndIntPtr *arg1 = 0 ;
  long long arg2 ;
  
  arg1 = (ndIntPtr *) carg1;
  arg2 = (long long) carg2;
  if (arg1) (arg1)->m_int = arg2;
}


SWIGEXPORTC long long ndIntPtr_m_int_get(SwigObj* carg1) {
  long long cppresult;
  ndIntPtr *arg1 = 0 ;
  long long result;
  
  arg1 = (ndIntPtr *) carg1;
  cppresult = (long long) ((arg1)->m_int);
  result = (long long)cppresult;
  return result;
}


SWIGEXPORTC void ndIntPtr_delete(SwigObj* carg1) {
  ndIntPtr *arg1 = 0 ;
  
  arg1 = (ndIntPtr *) carg1;
  delete arg1;
}


SWIGEXPORTC void ndDoubleInt_m_ptr_set(SwigObj* carg1, void * carg2) {
  ndDoubleInt *arg1 = 0 ;
  void *arg2 = 0 ;
  
  arg1 = (ndDoubleInt *) carg1;
  arg2 = (void *) carg2;
  if (arg1) (arg1)->m_ptr = arg2;
}


SWIGEXPORTC void * ndDoubleInt_m_ptr_get(SwigObj* carg1) {
  void *cppresult;
  ndDoubleInt *arg1 = 0 ;
  void * result;
  
  arg1 = (ndDoubleInt *) carg1;
  cppresult = (void *) ((arg1)->m_ptr);
  result = (void *)cppresult;
  return result;
}


SWIGEXPORTC void ndDoubleInt_m_int_set(SwigObj* carg1, long long carg2) {
  ndDoubleInt *arg1 = 0 ;
  long long arg2 ;
  
  arg1 = (ndDoubleInt *) carg1;
  arg2 = (long long) carg2;
  if (arg1) (arg1)->m_int = arg2;
}


SWIGEXPORTC long long ndDoubleInt_m_int_get(SwigObj* carg1) {
  long long cppresult;
  ndDoubleInt *arg1 = 0 ;
  long long result;
  
  arg1 = (ndDoubleInt *) carg1;
  cppresult = (long long) ((arg1)->m_int);
  result = (long long)cppresult;
  return result;
}


SWIGEXPORTC void ndDoubleInt_m_float_set(SwigObj* carg1, double carg2) {
  ndDoubleInt *arg1 = 0 ;
  double arg2 ;
  
  arg1 = (ndDoubleInt *) carg1;
  arg2 = (double) carg2;
  if (arg1) (arg1)->m_float = arg2;
}


SWIGEXPORTC double ndDoubleInt_m_float_get(SwigObj* carg1) {
  double cppresult;
  ndDoubleInt *arg1 = 0 ;
  double result;
  
  arg1 = (ndDoubleInt *) carg1;
  cppresult = (double) ((arg1)->m_float);
  result = (double)cppresult;
  return result;
}


SWIGEXPORTC SwigObj* ndDoubleInt_new() {
  ndDoubleInt *cppresult;
  SwigObj* result;
  
  cppresult = (ndDoubleInt *)new ndDoubleInt();
  result = (SwigObj*) cppresult;
  return result;
}


SWIGEXPORTC void ndDoubleInt_delete(SwigObj* carg1) {
  ndDoubleInt *arg1 = 0 ;
  
  arg1 = (ndDoubleInt *) carg1;
  delete arg1;
}


SWIGEXPORTC void ndTriplex_m_x_set(SwigObj* carg1, float carg2) {
  ndTriplex *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (ndTriplex *) carg1;
  arg2 = (float) carg2;
  if (arg1) (arg1)->m_x = arg2;
}


SWIGEXPORTC float ndTriplex_m_x_get(SwigObj* carg1) {
  float cppresult;
  ndTriplex *arg1 = 0 ;
  float result;
  
  arg1 = (ndTriplex *) carg1;
  cppresult = (float) ((arg1)->m_x);
  result = (float)cppresult;
  return result;
}


SWIGEXPORTC void ndTriplex_m_y_set(SwigObj* carg1, float carg2) {
  ndTriplex *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (ndTriplex *) carg1;
  arg2 = (float) carg2;
  if (arg1) (arg1)->m_y = arg2;
}


SWIGEXPORTC float ndTriplex_m_y_get(SwigObj* carg1) {
  float cppresult;
  ndTriplex *arg1 = 0 ;
  float result;
  
  arg1 = (ndTriplex *) carg1;
  cppresult = (float) ((arg1)->m_y);
  result = (float)cppresult;
  return result;
}


SWIGEXPORTC void ndTriplex_m_z_set(SwigObj* carg1, float carg2) {
  ndTriplex *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (ndTriplex *) carg1;
  arg2 = (float) carg2;
  if (arg1) (arg1)->m_z = arg2;
}


SWIGEXPORTC float ndTriplex_m_z_get(SwigObj* carg1) {
  float cppresult;
  ndTriplex *arg1 = 0 ;
  float result;
  
  arg1 = (ndTriplex *) carg1;
  cppresult = (float) ((arg1)->m_z);
  result = (float)cppresult;
  return result;
}


SWIGEXPORTC SwigObj* ndTriplex_new() {
  ndTriplex *cppresult;
  SwigObj* result;
  
  cppresult = (ndTriplex *)new ndTriplex();
  result = (SwigObj*) cppresult;
  return result;
}


SWIGEXPORTC void ndTriplex_delete(SwigObj* carg1) {
  ndTriplex *arg1 = 0 ;
  
  arg1 = (ndTriplex *) carg1;
  delete arg1;
}


SWIGEXPORTC SwigObj* ndTriplexReal_new() {
  ndTriplexReal *cppresult;
  SwigObj* result;
  
  cppresult = (ndTriplexReal *)new ndTriplexReal();
  result = (SwigObj*) cppresult;
  return result;
}


SWIGEXPORTC SwigObj* ndTriplexReal_new_f_f_f(float carg1, float carg2, float carg3) {
  ndTriplexReal *cppresult;
  ndReal arg1 ;
  ndReal arg2 ;
  ndReal arg3 ;
  SwigObj* result;
  
  arg1 = (ndReal) carg1;
  arg2 = (ndReal) carg2;
  arg3 = (ndReal) carg3;
  cppresult = (ndTriplexReal *)new ndTriplexReal(arg1,arg2,arg3);
  result = (SwigObj*) cppresult;
  return result;
}


SWIGEXPORTC void ndTriplexReal_m_x_set(SwigObj* carg1, float carg2) {
  ndTriplexReal *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (ndTriplexReal *) carg1;
  arg2 = (float) carg2;
  if (arg1) (arg1)->m_x = arg2;
}


SWIGEXPORTC float ndTriplexReal_m_x_get(SwigObj* carg1) {
  float cppresult;
  ndTriplexReal *arg1 = 0 ;
  float result;
  
  arg1 = (ndTriplexReal *) carg1;
  cppresult = (float) ((arg1)->m_x);
  result = (float)cppresult;
  return result;
}


SWIGEXPORTC void ndTriplexReal_m_y_set(SwigObj* carg1, float carg2) {
  ndTriplexReal *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (ndTriplexReal *) carg1;
  arg2 = (float) carg2;
  if (arg1) (arg1)->m_y = arg2;
}


SWIGEXPORTC float ndTriplexReal_m_y_get(SwigObj* carg1) {
  float cppresult;
  ndTriplexReal *arg1 = 0 ;
  float result;
  
  arg1 = (ndTriplexReal *) carg1;
  cppresult = (float) ((arg1)->m_y);
  result = (float)cppresult;
  return result;
}


SWIGEXPORTC void ndTriplexReal_m_z_set(SwigObj* carg1, float carg2) {
  ndTriplexReal *arg1 = 0 ;
  float arg2 ;
  
  arg1 = (ndTriplexReal *) carg1;
  arg2 = (float) carg2;
  if (arg1) (arg1)->m_z = arg2;
}


SWIGEXPORTC float ndTriplexReal_m_z_get(SwigObj* carg1) {
  float cppresult;
  ndTriplexReal *arg1 = 0 ;
  float result;
  
  arg1 = (ndTriplexReal *) carg1;
  cppresult = (float) ((arg1)->m_z);
  result = (float)cppresult;
  return result;
}


SWIGEXPORTC void ndTriplexReal_delete(SwigObj* carg1) {
  ndTriplexReal *arg1 = 0 ;
  
  arg1 = (ndTriplexReal *) carg1;
  delete arg1;
}


SWIGEXPORTC SwigObj* NewtonWorld_new() {
  NewtonWorld *cppresult;
  SwigObj* result;
  
  cppresult = (NewtonWorld *)new NewtonWorld();
  result = (SwigObj*) cppresult;
  return result;
}


SWIGEXPORTC void NewtonWorld_delete(SwigObj* carg1) {
  NewtonWorld *arg1 = 0 ;
  
  arg1 = (NewtonWorld *) carg1;
  delete arg1;
}


SWIGEXPORTC void NewtonWorld_Update(SwigObj* carg1, float carg2) {
  NewtonWorld *arg1 = 0 ;
  ndFloat32 arg2 ;
  
  arg1 = (NewtonWorld *) carg1;
  arg2 = (ndFloat32) carg2;
  (arg1)->Update(arg2);
}


SWIGEXPORTC void NewtonWorld_SetSubSteps(SwigObj* carg1, int carg2) {
  NewtonWorld *arg1 = 0 ;
  ndInt32 arg2 ;
  
  arg1 = (NewtonWorld *) carg1;
  arg2 = (ndInt32) carg2;
  (arg1)->SetSubSteps(arg2);
}


SWIGEXPORTC void NewtonWorld_SetIterations(SwigObj* carg1, int carg2) {
  NewtonWorld *arg1 = 0 ;
  ndInt32 arg2 ;
  
  arg1 = (NewtonWorld *) carg1;
  arg2 = (ndInt32) carg2;
  (arg1)->SetIterations(arg2);
}


#ifdef __cplusplus
}
#endif

